# Generated by Django 4.1.7 on 2023-03-19 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 12, 9, 47, 195109, tzinfo=datetime.timezone.utc)),
        ),
    ]
